server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/relics?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true


mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml

# JWT配置
jwt:
  # 使用长度至少为32个字符的密钥（256位）
  secret: mySecretKey123456789012345678901234567890ABCDEFGHIJKLMNOPQRST
  expiration: 86400 # 24小时

# 日志配置
logging:
  level:
    com.ling: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
