server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/relics?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #????????
    idle-timeout: 180000 #?????????????600000?10???
    maximum-pool-size: 25 #????????????10
    auto-commit: true  #?????????????????????,????true
    max-lifetime: 1800000 #??????????????????0???????????1800000?30??
    connection-timeout: 30000 #?????????,??30???30000
    connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml


