server:
  port: 8080

spring:
  datasource: # MySQL数据源配置（用于用户登录等核心业务）
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/relics?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true

  ai:
    vectorstore:
      pgvector: # PostgreSQL数据源配置（用于向量存储）
        url: jdbc:postgresql://localhost:5433/springai
        username: postgres
        password: postgres
    openai:

      chat:
        options:
          model: gemini-2.5-pro
#          model: gpt-4.1-mini
      embedding:
        options:
          num-batch: 1536
          model: text-embedding-3-small
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/mcpserver/mcp-server-sql.json
  # Jackson JSON序列化配置
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    # 序列化配置
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    # 反序列化配置
    deserialization:
      fail-on-unknown-properties: false
    # 默认属性包含策略
    default-property-inclusion: non_null
    # 属性命名策略
    property-naming-strategy: LOWER_CAMEL_CASE

mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

# Redis
redis:
  sdk:
    config:
      host: localhost
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# JWT配置
jwt:
  # 使用长度至少为32个字符的密钥（256位）
  secret: dsafasdfasdfasf
  expiration: 8640000 # 24小时

# 日志配置
logging:
  level:
    root: INFO
    com.ling.trigger.listener: INFO
    com.ling.domain.sensor: INFO
    org.springframework.integration.mqtt: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger文档配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: method
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# MQTT配置
mqtt:
  broker:
    url: tcp://117.72.63.151:1883
  client:
    id: relics-preservation-client
  username: dowithout
  password: dowithout
  topics:
    ems,light_intensity_1

# 传感器数据配置
sensor:
  data:
    # 批量处理大小
    batch:
      size: 100
      # 批处理间隔(毫秒)
      interval: 30000
    # 采样率(每N条数据采样1条)
    sample:
      rate: 10
    # 阈值判断
    threshold:
      enabled: true

# elasticsearch配置
elasticsearch:
  # 自定义属性---设置是否开启ES,false表不开窍ES
  open: true
  # es集群名称,如果下载es设置了集群名称,则使用配置的集群名称
  clusterName:
  hosts: localhost:9200
  # es 请求方式
  scheme: http
  # es 连接超时时间
  connectTimeOut: 1000
  # es socket 连接超时时间
  socketTimeOut: 30000
  # es 请求超时时间
  connectionRequestTimeOut: 500
  # es 最大连接数
  maxConnectNum: 100
  # es 每个路由的最大连接数
  maxConnectNumPerRoute: 100

